{ ... }:
{
  # Parametric S3-compatible artifact-store recipe, mirroring
  # `mcl.attic-cache-host`. The infra repo (or any consumer) instantiates
  # `mcl.s3-artifact-store` with its own domain, network ACL, and the set of
  # buckets it wants to host — each with an optional lifecycle expiry. This
  # module owns the generic machinery (the Garage S3 server, the nginx vhost
  # with the same defence-in-depth ACL + TLS, idempotent bucket + lifecycle
  # bootstrap, the on-host `mcl-garage` admin wrapper that mints/scopes S3
  # keys, and the published inventory); the consumer owns the policy (which
  # buckets, what CIDRs, the RPC/admin secret).
  #
  # Defence-in-depth, identical to the Attic cache:
  #   Layer 1 (VPN gate): the S3 + web endpoints are reachable ONLY through
  #     nginx, which enforces `allow <cidr>; ... deny all;` on every method.
  #     Garage itself binds loopback, so it is never publicly routable.
  #   Layer 2 (client credentials): every request must carry a valid S3
  #     access-key/secret (SigV4). Anonymous or invalid credentials are
  #     rejected by Garage. Keys are minted on-host by `mcl-garage` and are
  #     bucket-scoped (least-privilege: CI gets write to the artifacts bucket
  #     only), the direct analog of Attic `--push`/`--pull` tokens.
  flake.modules.nixos.mcl-s3-artifact-store =
    {
      config,
      lib,
      pkgs,
      ...
    }:
    let
      cfg = config.mcl.s3-artifact-store;
      inherit (lib)
        mkEnableOption
        mkIf
        mkOption
        types
        concatMapStringsSep
        concatStringsSep
        escapeShellArg
        ;

      domain = cfg.domain;

      # Garage listen ports (loopback only; nginx is the sole public ingress).
      s3Port = cfg.s3Port;
      webPort = cfg.webPort;
      rpcPort = cfg.rpcPort;
      adminPort = cfg.adminPort;

      stateDir = "/var/lib/garage";
      bootstrapDir = "/var/lib/s3-artifact-store-bootstrap";
      bootstrapMarker = "${bootstrapDir}/.store-bootstrapped";
      # Key IDs of buckets/keys already created are recorded here so the
      # bootstrap is idempotent across reboots and redeploys.
      inventoryFile = "${bootstrapDir}/managed-buckets.json";

      localS3Endpoint = "http://127.0.0.1:${toString s3Port}";
      publicEndpoint = "https://${domain}/";

      networkAllowDirectives = concatMapStringsSep "\n        " (
        cidr: "allow ${cidr};"
      ) cfg.networkAcl.allow;
      networkAcl = ''
        ${networkAllowDirectives}
        deny all;
      '';

      # Published, secret-free inventory of the managed buckets. Consulted by
      # operator tooling and the CI-configuration scripts.
      managedInventory = {
        version = 1;
        endpoint = publicEndpoint;
        region = cfg.region;
        buckets = map (b: {
          inherit (b) name;
          lifecycleExpiryDays = b.lifecycleExpiryDays;
        }) cfg.buckets;
        notes = [
          "Generated by mcl.s3-artifact-store. Access is gated by the nginx network ACL (allow ${concatStringsSep ", " cfg.networkAcl.allow}; deny all) PLUS a valid S3 access-key/secret (SigV4). Two-credential, mirroring the Attic cache."
          "S3 keys are minted on-host by `mcl-garage` and are bucket-scoped (least-privilege). Secrets are deliberately absent from this inventory."
        ];
      };
      managedInventoryJson = builtins.toJSON managedInventory;
      managedInventoryFile = pkgs.writeText "s3-artifact-store-buckets.json" managedInventoryJson;

      # ── on-host admin wrapper: the `mcl-atticadm` analog ────────────────────
      # Sources the Garage environment file (RPC secret + admin token) and
      # execs the real `garage` CLI against the checked /etc/garage.toml. The
      # only authority it grants is "administer the local Garage node" (create
      # buckets, mint + scope S3 keys) — exactly what an operator needs to
      # provision a CI credential, and nothing input-controlled escalates.
      mcl-garage = pkgs.writeShellScriptBin "mcl-garage" ''
        set -euo pipefail
        if [[ ! -r ${escapeShellArg cfg.environmentFile} ]]; then
          echo "mcl-garage: cannot read Garage environment file (must run as root)" >&2
          exit 1
        fi
        set -a
        # shellcheck disable=SC1090
        source ${escapeShellArg cfg.environmentFile}
        set +a
        # Garage reads GARAGE_RPC_SECRET / GARAGE_ADMIN_TOKEN from the env and
        # the node/region config from /etc/garage.toml.
        exec ${cfg.package}/bin/garage -c /etc/garage.toml "$@"
      '';

      # Convenience wrapper that mints a bucket-scoped S3 key and prints it as
      # JSON `{ "keyId": ..., "secretKey": ... }`. Used by the infra CI
      # provisioning script (the `issue-ci-push-token.sh` analog). Access ==
      # "read" | "write" | "owner"; multiple buckets may be granted.
      #
      # Usage: mcl-garage-issue-key <name> <access> <bucket> [<bucket> ...]
      mcl-garage-issue-key = pkgs.writeShellApplication {
        name = "mcl-garage-issue-key";
        runtimeInputs = [
          mcl-garage
          pkgs.jq
        ];
        text = ''
          set -euo pipefail
          if [[ $# -lt 3 ]]; then
            echo "usage: mcl-garage-issue-key <name> <read|write|owner> <bucket> [<bucket> ...]" >&2
            exit 2
          fi
          name="$1"; access="$2"; shift 2
          case "$access" in
            read|write|owner) ;;
            *) echo "mcl-garage-issue-key: access must be read|write|owner" >&2; exit 2 ;;
          esac

          # Garage reveals a key's secret only at creation time (like an Attic
          # token stream). We create a fresh key each invocation
          # (rotation-friendly). The CLI prints `Key ID: GK...` and
          # `Secret key: ...` (case-insensitive labels).
          # All human-readable CLI chatter goes to stderr so this script's
          # STDOUT is exactly one line of JSON — the caller pipes it straight
          # into `jq`/`gh secret set`, exactly like an Attic token stream.
          created=$(mcl-garage key create "$name")
          keyId=$(printf '%s\n' "$created" | grep -oiE 'Key ID:[[:space:]]*GK[0-9a-f]+' | head -n1 | grep -oE 'GK[0-9a-f]+' | head -n1 || true)
          secret=$(printf '%s\n' "$created" | grep -oiE 'Secret key:[[:space:]]*[0-9a-f]+' | head -n1 | grep -oE '[0-9a-f]{16,}' | head -n1 || true)
          if [[ -z "$keyId" || -z "$secret" ]]; then
            # Fall back to `key info --show-secret` for CLI variants whose
            # `create` output format differs.
            info=$(mcl-garage key info "$name" --show-secret)
            keyId=$(printf '%s\n' "$info" | grep -oE 'GK[0-9a-f]+' | head -n1 || true)
            secret=$(printf '%s\n' "$info" | grep -oiE 'Secret key:[[:space:]]*[0-9a-f]+' | head -n1 | grep -oE '[0-9a-f]{16,}' | head -n1 || true)
          fi
          if [[ -z "$keyId" || -z "$secret" ]]; then
            echo "mcl-garage-issue-key: could not parse key id/secret from garage output" >&2
            exit 1
          fi
          for bucket in "$@"; do
            case "$access" in
              read)  mcl-garage bucket allow "$bucket" --read --key "$keyId" >&2 ;;
              write) mcl-garage bucket allow "$bucket" --read --write --key "$keyId" >&2 ;;
              owner) mcl-garage bucket allow "$bucket" --read --write --owner --key "$keyId" >&2 ;;
            esac
          done
          jq -cn --arg k "$keyId" --arg s "$secret" '{keyId:$k, secretKey:$s}'
        '';
      };

      # ── idempotent bootstrap ───────────────────────────────────────────────
      # On every boot: ensure the single-node layout is applied, then create
      # each managed bucket and apply its S3 lifecycle expiry (mirroring the
      # Attic `retention-period`). Runs only local API calls; needs no VPN.
      storeBootstrap = pkgs.writeShellApplication {
        name = "s3-artifact-store-bootstrap";
        runtimeInputs = [
          mcl-garage
          pkgs.awscli2
          pkgs.coreutils
          pkgs.jq
        ];
        text = ''
          set -euo pipefail

          stateDir=${escapeShellArg bootstrapDir}
          marker=${escapeShellArg bootstrapMarker}
          inventorySource=${escapeShellArg managedInventoryFile}
          inventory="$stateDir/managed-buckets.json"

          install -d -m 0750 -o root -g root "$stateDir"
          cp -- "$inventorySource" "$inventory"
          chmod 0640 "$inventory"

          # Wait for the admin API so `garage status` works.
          for _ in $(seq 1 60); do
            if mcl-garage status >/dev/null 2>&1; then
              break
            fi
            sleep 1
          done

          # One-time single-node layout: assign this node full capacity so it
          # can hold data, then apply the pending version. Once a role is
          # assigned to the node id, re-running is a no-op.
          nodeId=$(mcl-garage node id -q 2>/dev/null | cut -d'@' -f1 || true)
          if [[ -n "$nodeId" ]]; then
            layout=$(mcl-garage layout show 2>/dev/null || true)
            # A node with an assigned role appears in the layout table with a
            # non-"NO ROLE" capacity line; if it is not yet assigned, assign it.
            if ! printf '%s\n' "$layout" | grep -q "''${nodeId:0:12}"; then
              mcl-garage layout assign -z ${escapeShellArg cfg.zone} -c ${escapeShellArg cfg.nodeCapacity} "$nodeId" || true
              # `garage layout show` prints "Current cluster layout version: N";
              # `apply` needs the *pending* version, N+1.
              cur=$(mcl-garage layout show 2>/dev/null | grep -oiE 'layout version:?[[:space:]]*[0-9]+' | grep -oE '[0-9]+' | tail -n1 || echo 0)
              mcl-garage layout apply --version "$((cur + 1))" || true
            fi
          fi

          # Pass 1: create every managed bucket (must exist before a key can be
          # granted access to it, and before lifecycle can be applied).
          mapfile -t bucketNames < <(jq -r '.buckets[].name' "$inventory")
          for name in "''${bucketNames[@]}"; do
            if ! mcl-garage bucket info "$name" >/dev/null 2>&1; then
              mcl-garage bucket create "$name"
              echo "s3-artifact-store-bootstrap: created bucket '$name'."
            else
              echo "s3-artifact-store-bootstrap: bucket '$name' exists; reusing."
            fi
          done

          # Mint a dedicated owner key scoped to the managed buckets for
          # lifecycle administration; its secret never leaves this host. This
          # is also what points aws-cli at the loopback S3 endpoint below.
          bootstrapKeyJson=$(${lib.getExe mcl-garage-issue-key} s3-artifact-store-bootstrap owner "''${bucketNames[@]}") || true

          # Pass 2: apply each bucket's S3 lifecycle expiry (mirrors the Attic
          # retention-period / artifact retention-days).
          if [[ -n "$bootstrapKeyJson" ]]; then
            keyId=$(jq -r '.keyId' <<<"$bootstrapKeyJson")
            secret=$(jq -r '.secretKey' <<<"$bootstrapKeyJson")
            jq -c '.buckets[]' "$inventory" | while IFS= read -r bucket_json; do
              name=$(jq -r '.name' <<<"$bucket_json")
              expiry=$(jq -r '.lifecycleExpiryDays // empty' <<<"$bucket_json")
              [[ -n "$expiry" ]] || continue
              cat > "$stateDir/lifecycle.json" <<JSON
          {"Rules":[{"ID":"expire-artifacts","Status":"Enabled","Filter":{"Prefix":""},"Expiration":{"Days":$expiry}}]}
          JSON
              if AWS_ACCESS_KEY_ID="$keyId" \
                 AWS_SECRET_ACCESS_KEY="$secret" \
                 AWS_EC2_METADATA_DISABLED=true \
                   aws --endpoint-url ${escapeShellArg localS3Endpoint} \
                       --region ${escapeShellArg cfg.region} \
                       s3api put-bucket-lifecycle-configuration \
                       --bucket "$name" \
                       --lifecycle-configuration "file://$stateDir/lifecycle.json"
              then
                echo "s3-artifact-store-bootstrap: lifecycle expiry ''${expiry}d set on '$name'."
              else
                echo "s3-artifact-store-bootstrap: WARNING could not set lifecycle on '$name' (continuing)." >&2
              fi
              rm -f "$stateDir/lifecycle.json"
            done
          fi

          touch "$marker"
          echo "s3-artifact-store-bootstrap: complete."
        '';
      };

      bucketType = types.submodule (
        { ... }:
        {
          options = {
            name = mkOption {
              type = types.str;
              description = "S3 bucket name (path segment under the endpoint).";
            };
            lifecycleExpiryDays = mkOption {
              type = types.nullOr types.ints.positive;
              default = null;
              example = 1;
              description = ''
                If set, objects auto-expire after this many days via an S3
                lifecycle rule — mirroring the GitHub Actions artifact
                `retention-days`, so the bucket does not grow unbounded.
              '';
            };
          };
        }
      );
    in
    {
      options.mcl.s3-artifact-store = {
        enable = mkEnableOption "the parametric S3-compatible artifact store (Garage + nginx ACL + bucket/lifecycle bootstrap)";

        domain = mkOption {
          type = types.str;
          example = "s3.metacraft-labs.com";
          description = "Public hostname for the S3 endpoint vhost.";
        };

        package = mkOption {
          type = types.package;
          default = pkgs.garage;
          defaultText = lib.literalMD "`pkgs.garage`";
          description = "Garage package providing the S3 server + admin CLI.";
        };

        region = mkOption {
          type = types.str;
          default = "garage";
          description = "S3 region advertised by Garage (clients must match).";
        };

        zone = mkOption {
          type = types.str;
          default = "mcl";
          description = "Garage layout zone for this (single) node.";
        };

        nodeCapacity = mkOption {
          type = types.str;
          default = "1T";
          description = "Garage layout capacity assigned to this node.";
        };

        s3Port = mkOption {
          type = types.port;
          default = 3900;
          description = "Loopback S3 API port (proxied by nginx).";
        };
        webPort = mkOption {
          type = types.port;
          default = 3902;
          description = "Loopback S3 web (static website) port.";
        };
        rpcPort = mkOption {
          type = types.port;
          default = 3901;
          description = "Loopback Garage RPC port (single node).";
        };
        adminPort = mkOption {
          type = types.port;
          default = 3903;
          description = "Loopback Garage admin API port.";
        };

        environmentFile = mkOption {
          type = types.path;
          description = ''
            Path to the Garage environment file (e.g. an agenix-decrypted
            runtime path) providing GARAGE_RPC_SECRET and GARAGE_ADMIN_TOKEN.
            The `mcl-garage` admin wrapper and the garage service both source
            it. Rotating GARAGE_RPC_SECRET reprovisions node identity;
            GARAGE_ADMIN_TOKEN gates the admin API only.
          '';
        };

        metadataDir = mkOption {
          type = types.str;
          default = "${stateDir}/meta";
          description = "Garage metadata directory (put on fast disk).";
        };
        dataDir = mkOption {
          type = types.str;
          default = "${stateDir}/data";
          description = "Garage object data-block directory (the dedicated /storage dataset in prod).";
        };

        networkAcl.allow = mkOption {
          type = types.listOf types.str;
          example = [
            "100.64.0.0/10"
            "192.168.100.0/24"
          ];
          description = "Source CIDRs allowed by nginx (NetBird overlay + LAN). Every other source is denied on every method.";
        };

        buckets = mkOption {
          type = types.listOf bucketType;
          description = "Buckets to host, each with an optional lifecycle expiry.";
        };
      };

      config = mkIf cfg.enable {
        assertions = [
          {
            assertion = cfg.buckets != [ ];
            message = "mcl.s3-artifact-store: at least one bucket must be configured.";
          }
          {
            assertion = cfg.networkAcl.allow != [ ];
            message = "mcl.s3-artifact-store: networkAcl.allow must not be empty — the store must never be publicly routable.";
          }
        ];

        environment.systemPackages = [
          mcl-garage
          mcl-garage-issue-key
        ];

        services.garage = {
          enable = true;
          package = cfg.package;
          environmentFile = cfg.environmentFile;
          settings = {
            metadata_dir = cfg.metadataDir;
            data_dir = cfg.dataDir;
            db_engine = "lmdb";

            # Single node: one replica, no redundancy.
            replication_factor = 1;

            # RPC secret comes from the environment file (GARAGE_RPC_SECRET).
            rpc_bind_addr = "127.0.0.1:${toString rpcPort}";
            rpc_public_addr = "127.0.0.1:${toString rpcPort}";

            s3_api = {
              api_bind_addr = "127.0.0.1:${toString s3Port}";
              s3_region = cfg.region;
              # Path-style access; nginx terminates TLS at ${domain}.
              root_domain = ".s3.${domain}";
            };

            s3_web = {
              bind_addr = "127.0.0.1:${toString webPort}";
              root_domain = ".web.${domain}";
              index = "index.html";
            };

            admin = {
              api_bind_addr = "127.0.0.1:${toString adminPort}";
              # admin_token / metrics_token come from the environment file
              # (GARAGE_ADMIN_TOKEN); the admin API is loopback-only regardless.
            };
          };
        };

        systemd.services.garage.restartTriggers = [ cfg.environmentFile ];

        systemd.tmpfiles.rules = [
          "d ${bootstrapDir} 0750 root root -"
          "d ${cfg.metadataDir} 0700 garage garage -"
          "d ${cfg.dataDir} 0700 garage garage -"
        ];

        systemd.services.s3-artifact-store-bootstrap = {
          description = "Idempotent bootstrap of managed S3 buckets + lifecycle";
          after = [
            "garage.service"
            "network-online.target"
          ];
          wants = [ "network-online.target" ];
          requires = [ "garage.service" ];
          wantedBy = [ "multi-user.target" ];
          serviceConfig = {
            Type = "oneshot";
            RemainAfterExit = true;
            ExecStart = "${storeBootstrap}/bin/s3-artifact-store-bootstrap";
            TimeoutStartSec = "180s";
          };
        };

        # Published inventory for operators + CI-provisioning scripts.
        environment.etc."s3-artifact-store/managed-buckets.json".text = managedInventoryJson + "\n";
        environment.etc."s3-artifact-store/endpoint.env".text = ''
          MCL_S3_ENDPOINT=${publicEndpoint}
          MCL_S3_REGION=${cfg.region}
        '';

        # ── nginx: layer-1 VPN gate + TLS, identical model to the Attic vhost ──
        services.nginx.commonHttpConfig = lib.mkAfter ''
          log_format mcl_s3_artifact_store escape=json '{"time":"$time_iso8601","remote_addr":"$remote_addr","host":"$host","method":"$request_method","uri":"$request_uri","status":"$status","request_length":"$request_length","body_bytes_sent":"$body_bytes_sent","upstream_status":"$upstream_status","request_time":"$request_time","upstream_response_time":"$upstream_response_time"}';
        '';

        services.nginx.virtualHosts.${domain} = {
          forceSSL = true;
          enableACME = true;
          acmeRoot = null;
          locations."/" = {
            extraConfig = ''
              access_log /var/log/nginx/s3-artifact-store.access.jsonl mcl_s3_artifact_store;
              ${networkAcl}
              # Artifacts can be large; match the Attic vhost's generous cap.
              client_max_body_size 10G;
              # SigV4 signs over the client's Host header — forward it verbatim
              # (NOT nginx's default upstream host) or Garage recomputes the
              # signature against 127.0.0.1 and rejects every authenticated
              # request as "Invalid signature".
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              # Stream request + response bodies so large multipart uploads and
              # downloads are not spooled to disk.
              proxy_request_buffering off;
              proxy_buffering off;
              proxy_http_version 1.1;
            '';
            proxyPass = "http://127.0.0.1:${toString s3Port}";
          };
        };
        security.acme.certs.${domain} = { };
      };
    };
}
