{
  imports = [
    ./cachix-deploy-metrics
    ./lido
    ./pyroscope
    ./aztec
    ./cachix-deploy
    ./folder-size-metrics
    ./deployment-event-metrics
    ./deployment
    ./netbird-with-agenix
    ./shard-split
    ./random-alerts
    ./tailscale-with-agenix
    ./host-info.nix
    ./secrets.nix
    ./mcl-disko
    ./pharos
    ./commands.nix
    ./attic-cache-host
    ./mcl-s3-artifact-store
    ./mcl-repro-binary-cache
    ./mcl-reprobuild
    ./mcl-repro-deploy-agent
    ./garm
    ./garm-fleet-alerts
    ./garm-fleet-external-checks
    ./github-actions-fit-exporter
    ./github-actions-fit-alerts
    ./runner-label-taxonomy
    ./vm-harness-serve
    ./vm-harness-serve/darwin.nix
    ./virtualisation/desktop-vms.nix
    ./nix-topology
    ./alertmanager-fleet-routing
  ];
}
