# GARM runner-fleet alerting — the GENERAL, parametric NixOS + package surface.
#
# Runner-Fleet-Capability-Pools-And-Remote-Driving RE1 (`t_fleet_alerting`).
#
# The company-agnostic alert-rule LIBRARY lives here (nixos-modules), per the
# campaign :repo_layering: — the concrete routing/targets/thresholds tuned for a
# specific fleet live in that operator's `infra`. This module:
#
#   * `services.garm-fleet-alerts` — renders the ./rules.nix library with the
#     operator's thresholds into `services.prometheus.ruleFiles`.
#   * `packages.garm-fleet-alert-rules` — the default-threshold render, so the
#     rules are build-testable with promtool WITHOUT any infra (the gate
#     checks/fleet-alerting.nix consumes it).
#
# The rule TEXT is generated by the pure ./rules.nix so the shipped file is the
# exact file `promtool test rules` replays (tests/fleet-alerting.test.yml) — the
# lesson the deployment-events rules learned the hard way (see the note atop
# infra/services/monitoring/prometheus.nix).
{ ... }:
{
  perSystem =
    { pkgs, lib, ... }:
    {
      # Default-threshold render — convenience + the gate's input.
      packages.garm-fleet-alert-rules = pkgs.writeText "garm-fleet-alerts.yml" (
        import ./rules.nix { inherit lib; }
      );
    };

  flake.modules.nixos.garm-fleet-alerts =
    {
      config,
      lib,
      pkgs,
      ...
    }:
    let
      cfg = config.services.garm-fleet-alerts;
      inherit (lib)
        mkEnableOption
        mkOption
        mkIf
        types
        ;

      rendered = import ./rules.nix {
        inherit lib;
        inherit (cfg)
          garmJob
          mode
          externalChecks
          webhookChecks
          webhookProbeJobRegex
          ;
        inherit (cfg.thresholds)
          providerCreateFailCount
          providerErrorRatioCrit
          rateLimitWarn
          rateLimitCrit
          ;
      };
    in
    {
      options.services.garm-fleet-alerts = {
        enable = mkEnableOption "the GARM runner-fleet Prometheus alert-rule library";

        garmJob = mkOption {
          type = types.str;
          default = "garm";
          description = "Prometheus scrape job that collects `garm_*` from the controllers.";
        };

        mode = mkOption {
          type = types.enum [
            "scaleset"
            "pool"
          ];
          default = "scaleset";
          description = ''
            Selects the capacity metric family. `scaleset` (live today) keys on
            `garm_scaleset_*`; `pool` keys on `garm_pool_*` after the Phase-C
            migration. See ./rules.nix for the scale-set-vs-pool starvation-join
            difference.
          '';
        };

        externalChecks = mkOption {
          type = types.bool;
          default = true;
          description = ''
            Emit the external-check alerts (GitHub App token minting; and, when
            `webhookChecks` is on, webhook delivery + endpoint probe) over the
            metrics published by `services.garm-fleet-external-checks`.
          '';
        };

        webhookChecks = mkOption {
          type = types.bool;
          default = false;
          description = ''
            Emit the webhook alert family (GARM-side HMAC failures + external
            delivery/probe checks). POST-PHASE-C only: in scale-set mode GARM
            long-polls GitHub and there are no webhooks, so `garm_webhook_received`
            never exists and there is no endpoint to probe. Default off until the
            public webhook endpoint (RC3) lands.
          '';
        };

        webhookProbeJobRegex = mkOption {
          type = types.str;
          default = ".*webhook.*";
          description = "Blackbox-exporter job regex that probes the public webhook endpoint(s).";
        };

        thresholds = {
          providerCreateFailCount = mkOption {
            type = types.int;
            default = 3;
            description = "CreateInstance failures within 15m that trip GarmProviderCreateFailures.";
          };
          providerErrorRatioCrit = mkOption {
            type = types.str;
            default = "0.2";
            description = "Provider error/operation ratio (over 15m) that trips GarmProviderHighErrorRatio.";
          };
          rateLimitWarn = mkOption {
            type = types.int;
            default = 200;
            description = "GitHub API requests-remaining warning threshold.";
          };
          rateLimitCrit = mkOption {
            type = types.int;
            default = 50;
            description = "GitHub API requests-remaining critical threshold.";
          };
        };
      };

      config = mkIf cfg.enable {
        services.prometheus.ruleFiles = [
          (pkgs.writeText "garm-fleet-alerts.yml" rendered)
        ];
      };
    };
}
