# Set the path to the GraphQL source code
graphQLSrc="$CARDANO_GRAPHQL_SRC"

# Set the path to the network configuration directory
export CARDANO_GRAPHQL_NETWORK_CONFIG_PATH="$CARDANO_TESTNET_DIR"/graphql-config

rm -rf $CARDANO_GRAPHQL_NETWORK_CONFIG_PATH
# Create directories for the cardano-db-sync and genesis configuration files
mkdir -p "$CARDANO_GRAPHQL_NETWORK_CONFIG_PATH"/testnet/cardano-db-sync
mkdir -p "$CARDANO_GRAPHQL_NETWORK_CONFIG_PATH"/testnet/genesis

# Copy the cardano-db-sync configuration file to the network configuration directory
cp ${CARDANO_GRAPHQL_SRC}/config/network/testnet/cardano-db-sync/config.json "$CARDANO_GRAPHQL_NETWORK_CONFIG_PATH"/testnet/cardano-db-sync/config.json

# Copy the cardano-node configuration files to the network configuration directory
cp -r ${CARDANO_GRAPHQL_SRC}/config/network/testnet/cardano-node/ "$CARDANO_GRAPHQL_NETWORK_CONFIG_PATH"/testnet/

# Copy the genesis files to the network configuration directory
cp -r "$CARDANO_TESTNET_DIR"/byron/genesis.json "$CARDANO_GRAPHQL_NETWORK_CONFIG_PATH"/testnet/genesis/byron.json
cp -r "$CARDANO_TESTNET_DIR"/shelley/genesis.json "$CARDANO_GRAPHQL_NETWORK_CONFIG_PATH"/testnet/genesis/shelley.json
cp -r "$CARDANO_TESTNET_DIR"/shelley/genesis.alonzo.json "$CARDANO_GRAPHQL_NETWORK_CONFIG_PATH"/testnet/genesis/alonzo.json

# Generate and set the Shelley, Alonzo, and Byron genesis hashes
export SHELLEY_GENESIS_HASH=""
SHELLEY_GENESIS_HASH=$(grep 'ShelleyGenesisHash:' "$CARDANO_TESTNET_DIR"/configuration.yaml | cut -d ' ' -f 2)
export ALONZO_GENESIS_HASH=""
ALONZO_GENESIS_HASH=$(grep 'AlonzoGenesisHash:' "$CARDANO_TESTNET_DIR"/configuration.yaml | cut -d ' ' -f 2)
export BYRON_GENESIS_HASH=""
BYRON_GENESIS_HASH=$(grep 'ByronGenesisHash:' "$CARDANO_TESTNET_DIR"/configuration.yaml | cut -d ' ' -f 2)



echo "Generated Shelley genesis hash: $SHELLEY_GENESIS_HASH"
echo "Generated Alonzo genesis hash: $ALONZO_GENESIS_HASH"
echo "Generated Byron genesis hash: $BYRON_GENESIS_HASH"

# Grant read and write permissions to the GraphQL configuration directory and its contents
chmod -R a+rw "$CARDANO_TESTNET_DIR"/graphql-config/

# Replace the network name in the cardano-db-sync configuration file
sed -i 's/"NetworkName": "testnet"/"NetworkName": "privatenet"/' "$CARDANO_GRAPHQL_NETWORK_CONFIG_PATH"/testnet/cardano-db-sync/config.json

echo "Replaced network name in cardano-db-sync configuration file"

# Replace the topology address in the cardano-node configuration file
sed -i 's/relays-new.cardano-testnet.iohkdev.io/172.17.0.1/' "$CARDANO_GRAPHQL_NETWORK_CONFIG_PATH"/testnet/cardano-node/topology.json


echo "Replaced topology address in cardano-node configuration file"

# Replace the Shelley, Alonzo, and Byron genesis hashes in the cardano-node configuration file
sed -i -E "s/(\"ShelleyGenesisHash\": )\"[[:digit:]a-fA-F]+\"/\1\"$SHELLEY_GENESIS_HASH\"/" "$CARDANO_GRAPHQL_NETWORK_CONFIG_PATH"/testnet/cardano-node/config.json
sed -i -E "s/(\"AlonzoGenesisHash\": )\"[[:digit:]a-fA-F]+\"/\1\"$ALONZO_GENESIS_HASH\"/" "$CARDANO_GRAPHQL_NETWORK_CONFIG_PATH"/testnet/cardano-node/config.json
sed -i -E "s/(\"ByronGenesisHash\": )\"[[:digit:]a-fA-F]+\"/\1\"$BYRON_GENESIS_HASH\"/" "$CARDANO_GRAPHQL_NETWORK_CONFIG_PATH"/testnet/cardano-node/config.json

NODE_CONFIG_FILE="$CARDANO_GRAPHQL_NETWORK_CONFIG_PATH"/testnet/cardano-node/config.json
jq '.TestShelleyHardForkAtEpoch = 0' "$NODE_CONFIG_FILE" > tmp.json && mv tmp.json "$NODE_CONFIG_FILE"
jq '.TestAllegraHardForkAtEpoch = 0' "$NODE_CONFIG_FILE" > tmp.json && mv tmp.json "$NODE_CONFIG_FILE"
jq '.TestMaryHardForkAtEpoch = 0' "$NODE_CONFIG_FILE" > tmp.json && mv tmp.json "$NODE_CONFIG_FILE"
jq '.TestAlonzoHardForkAtEpoch = 0' "$NODE_CONFIG_FILE" > tmp.json && mv tmp.json "$NODE_CONFIG_FILE"

jq '.TestEnableDevelopmentHardForkEras = true' "$NODE_CONFIG_FILE" > tmp.json && mv tmp.json "$NODE_CONFIG_FILE"
jq '.TestEnableDevelopmentNetworkProtocols = true' "$NODE_CONFIG_FILE" > tmp.json && mv tmp.json "$NODE_CONFIG_FILE"
jq '.ApplicationVersion = 1' "$NODE_CONFIG_FILE" > tmp.json && mv tmp.json "$NODE_CONFIG_FILE"

echo "Start cardano graphql"

cd ${CARDANO_GRAPHQL_SRC}
#ls .
cat docker-compose.yml
echo $CARDANO_GRAPHQL_NETWORK_CONFIG_PATH
echo $CARDANO_GRAPHQL_SRC

CARDANO_GRAPHQL_NETWORK_CONFIG_PATH=$CARDANO_GRAPHQL_NETWORK_CONFIG_PATH \
DOCKER_BUILDKIT=1 \
COMPOSE_DOCKER_CLI_BUILD=1 \
NETWORK=testnet API_PORT=3102 \
HASURA_PORT=8092 OGMIOS_PORT=1339 \
POSTGRES_PORT=5434 \
docker compose -f $CARDANO_GRAPHQL_SRC/docker-compose.yml -p testnet up -d --build && docker compose -p testnet logs -f > "$CARDANO_GRAPHQL_NETWORK_CONFIG_PATH"/output.txt
echo "Graphql is started"
