name: Evaluate CI Matrix
description: Evaluate all packages, check cache status generate CI matrix and publish comment with the summary

inputs:
  is-initial:
    description: Is this the start of the CI workflow, or the end
    default: 'true'
    required: true
  cachix-cache:
    description: The name of the cachix cache to use
    required: true
  cachix-auth-token:
    description: Cachix auth token
    required: true
  trusted-public-keys:
    description: Trusted public keys
    required: true
  substituters:
    description: Substituters
    required: true
  flake_pre:
    description: Prefix for the flake to evaluate
    required: false
    default: ""
  flake_post:
    description: Postfix for the flake to evaluate
    required: false
    default: ""
  comment_matrix:
    description: Whether to post a comment/upload the matrix
    required: false
    default: true

outputs:
  matrix:
    description: 'Generated Matrix'
    value: ${{ steps.generate-matrix.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v27
      if: ${{ runner.environment == 'github-hosted' }}
      with:
        extra_nix_config: |
          accept-flake-config = true
          substituters = https://cache.nixos.org ${{inputs.substituters}}
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= ${{inputs.trusted-public-keys}}
          netrc-file = /home/runner/.config/nix/netrc
    - name: Configure Nix
      shell: bash
      run: |
        mkdir -p /home/runner/.config/nix
        echo "machine ${{inputs.cachix-cache}}.cachix.org password ${{inputs.cachix-auth-token}}" >> /home/runner/.config/nix/netrc

    - name: Generate CI Matrix
      id: generate-matrix
      shell: bash
      env:
        IS_INITIAL: ${{ inputs.is-initial }}
        CACHIX_CACHE: ${{ inputs.cachix-cache }}
        CACHIX_AUTH_TOKEN: ${{ inputs.cachix-auth-token }}
        FLAKE_PRE: ${{ inputs.flake_pre }}
        FLAKE_POST: ${{ inputs.flake_post }}
      run: nix run github:metacraft-labs/nixos-modules/feat/CD#mcl ci_matrix
