name: Evaluate CI Matrix
description: Evaluate all packages, check cache status generate CI matrix

inputs:
  is-initial:
    description: Is this the start of the CI workflow, or the end
    default: 'true'
    required: true
  cachix-cache:
    description: The name of the cachix cache to use
    required: true
  cachix-auth-token:
    description: Cachix auth token
    required: true
  trusted-public-keys:
    description: Trusted public keys
    required: true
  substituters:
    description: Substituters
    required: true
  flake_pre:
    description: Prefix for the flake to evaluate
    required: false
    default: ""
  flake_post:
    description: Postfix for the flake to evaluate
    required: false
    default: ""

outputs:
  matrix:
    description: 'Generated Matrix'
    value: ${{ steps.generate-matrix.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: metacraft-labs/nixos-modules/.github/install-nix@main
      with:
        cachix-cache: ${{ inputs.cachix-cache }}
        cachix-auth-token: ${{ inputs.cachix-auth-token }}
        trusted-public-keys: ${{ inputs.trusted-public-keys }}
        substituters: ${{ inputs.substituters }}

    - name: Generate CI Matrix
      id: generate-matrix
      shell: bash
      env:
        IS_INITIAL: ${{ inputs.is-initial }}
        CACHIX_CACHE: ${{ inputs.cachix-cache }}
        CACHIX_AUTH_TOKEN: ${{ inputs.cachix-auth-token }}
        FLAKE_PRE: ${{ inputs.flake_pre }}
        FLAKE_POST: ${{ inputs.flake_post }}
      run: |
        if [ "${{ github.repository }}" != "metacraft-labs/nixos-modules" ]; then
          nix run github:metacraft-labs/nixos-modules#mcl ci_matrix
        else
          nix run .#mcl ci_matrix
        fi
