{ ... }:
{
  # Parametric Attic cache-hosting recipe. The infra repo (or any consumer)
  # instantiates `mcl.attic-cache-host` with its own domain, network ACL, and
  # the set of caches it wants to host — each with an `access` policy that
  # selects the atticd visibility + nginx exposure. This module owns the
  # generic machinery (atticd settings, nginx vhost, idempotent cache
  # bootstrap, the atticadm token wrapper, the published inventory); the
  # consumer owns the policy (which caches, what access, the HS256 secret).
  flake.modules.nixos.mcl-attic-cache-host =
    {
      config,
      lib,
      pkgs,
      ...
    }:
    let
      cfg = config.mcl.attic-cache-host;
      port = cfg.port;
      domain = cfg.domain;

      bootstrapDir = "/var/lib/attic-cache-bootstrap";
      bootstrapPublicKey = "${bootstrapDir}/public-key.txt";
      bootstrapPublicKeyDir = "${bootstrapDir}/public-keys";
      bootstrapMarker = "${bootstrapDir}/.cache-bootstrapped";

      primaryCache = lib.findFirst (c: c.primary) (lib.head cfg.caches) cfg.caches;
      primaryCacheName = primaryCache.name;

      # `access` policy -> atticd visibility + how nginx exposes the cache.
      #   netbird-token   : atticd --private (token-gated pull) + network ACL on
      #                     every method. Two-credential: VPN AND a token.
      #   netbird-anon    : atticd --public (unauthenticated pull) + network ACL
      #                     on every method. VPN membership alone authorizes reads.
      #   public-internet : atticd --public + nginx allows unauthenticated GET
      #                     from anywhere; writes restricted to the network ACL.
      accessToVisibility = {
        netbird-token = "private";
        netbird-anon = "public";
        public-internet = "public";
      };
      # Caches whose GET is exposed to the internet (no source ACL on reads).
      internetReadCaches = builtins.filter (c: c.access == "public-internet") cfg.caches;
      internetReadCacheNames = lib.sort lib.lessThan (map (c: c.name) internetReadCaches);

      networkAllowDirectives = lib.concatMapStringsSep "\n        " (
        cidr: "allow ${cidr};"
      ) cfg.networkAcl.allow;
      networkAcl = ''
        ${networkAllowDirectives}
        deny all;
      '';

      cacheWithPaths =
        cache:
        cache
        // {
          visibility = accessToVisibility.${cache.access};
          endpoint = "https://${domain}/";
          substituter = "https://${domain}/${cache.name}";
          publicKeyFile = "${bootstrapPublicKeyDir}/${cache.name}.txt";
          legacyPublicKeyFile = if cache.name == primaryCacheName then bootstrapPublicKey else null;
        };

      managedCaches = map cacheWithPaths cfg.caches;

      managedCacheInventory = {
        version = 1;
        endpoint = "https://${domain}/";
        primaryCache = primaryCacheName;
        caches = managedCaches;
        notes = [
          "Generated by mcl.attic-cache-host. Access is gated by the nginx network ACL (allow ${lib.concatStringsSep ", " cfg.networkAcl.allow}; deny all) plus, for private caches, an Attic token."
          "`visibility` derives from each cache's `access`: netbird-token=private (token-gated reads), netbird-anon/public-internet=public (unauthenticated pull)."
          "Bearer tokens and other secrets are deliberately absent from this inventory."
        ];
      };
      managedCacheInventoryJson = builtins.toJSON managedCacheInventory;
      managedCacheInventoryFile = pkgs.writeText "attic-managed-caches.json" managedCacheInventoryJson;
      managedCacheInventoryTsv = ''
        name	visibility	access	retention	substituter	public_key_file	legacy_public_key_file
      ''
      + lib.concatMapStrings (
        cache:
        let
          legacyPublicKeyFile = if cache.legacyPublicKeyFile == null then "" else cache.legacyPublicKeyFile;
        in
        "${cache.name}\t${cache.visibility}\t${cache.access}\t${cache.retention}\t${cache.substituter}\t${cache.publicKeyFile}\t${legacyPublicKeyFile}\n"
      ) managedCaches;

      bootstrapTokenScopes = lib.concatMapStringsSep " " (
        cache:
        lib.concatStringsSep " " (
          map (scope: "${scope} ${lib.escapeShellArg cache.name}") [
            "--pull"
            "--push"
            "--create-cache"
            "--configure-cache"
            "--configure-cache-retention"
          ]
        )
      ) managedCaches;

      # Extract the `-f <path>` argument from atticd's ExecStart so atticadm
      # uses the exact same checked TOML config that atticd does.
      atticdExecStart = config.systemd.services.atticd.serviceConfig.ExecStart;
      atticdConfigPath =
        let
          m = builtins.match ".*-f ([^ ]+) .*" atticdExecStart;
        in
        if m == null then
          throw "mcl.attic-cache-host: could not find -f <config> in atticd's ExecStart: ${atticdExecStart}"
        else
          builtins.head m;

      # Wrapper that sources the HS256 environment file before exec'ing
      # atticadm (so it can sign tokens). The consumer provides the env file
      # path (typically an agenix-decrypted runtime path).
      mcl-atticadm = pkgs.writeShellScriptBin "mcl-atticadm" ''
        set -euo pipefail
        if [[ ! -r ${cfg.environmentFile} ]]; then
          echo "mcl-atticadm: cannot read atticd environment file (must run as root)" >&2
          exit 1
        fi
        set -a
        # shellcheck disable=SC1090
        source ${cfg.environmentFile}
        set +a
        exec ${pkgs.attic-server}/bin/atticadm -f ${atticdConfigPath} "$@"
      '';

      cacheBootstrap = pkgs.writeShellApplication {
        name = "attic-cache-bootstrap";
        runtimeInputs = with pkgs; [
          attic-client
          coreutils
          curl
          gnused
          jq
        ];
        text = ''
          set -euo pipefail

          localEndpoint="http://127.0.0.1:${toString port}/"
          publicEndpoint="https://${domain}/"
          marker=${lib.escapeShellArg bootstrapMarker}
          publicKey=${lib.escapeShellArg bootstrapPublicKey}
          publicKeyDir=${lib.escapeShellArg bootstrapPublicKeyDir}
          stateDir=${lib.escapeShellArg bootstrapDir}
          inventorySource=${lib.escapeShellArg managedCacheInventoryFile}
          stateInventory="$stateDir/managed-caches.json"
          readableInventory="$stateDir/managed-caches.tsv"
          publicKeysJson="$stateDir/public-keys.json"
          publicKeysJsonl=$(mktemp)

          install -d -m 0755 -o root -g root "$stateDir"
          install -d -m 0755 -o root -g root "$publicKeyDir"
          cp -- "$inventorySource" "$stateInventory"
          chmod 0644 "$stateInventory"

          for _ in $(seq 1 60); do
            if curl --silent --output /dev/null --connect-timeout 1 \
                --max-time 2 "http://127.0.0.1:${toString port}/" 2>/dev/null; then
              break
            fi
            sleep 1
          done

          token=$(${mcl-atticadm}/bin/mcl-atticadm make-token \
            --sub atticd-cache-bootstrap \
            --validity 5m \
            ${bootstrapTokenScopes})

          install -d -m 0700 /root/.config/attic
          trap 'rm -rf /root/.config/attic; rm -f "$publicKeysJsonl"' EXIT INT TERM
          attic login local-bootstrap "$localEndpoint" "$token"

          jq -c '.caches[]' "$stateInventory" | while IFS= read -r cache_json; do
            cache_name=$(jq -r '.name' <<<"$cache_json")
            visibility=$(jq -r '.visibility' <<<"$cache_json")
            priority=$(jq -r '.priority' <<<"$cache_json")
            retention_mode=$(jq -r '.retention' <<<"$cache_json")
            retention_period=$(jq -r '.retentionPeriod // empty' <<<"$cache_json")
            public_key_file=$(jq -r '.publicKeyFile' <<<"$cache_json")
            substituter=$(jq -r '.substituter' <<<"$cache_json")

            case "$visibility" in
              public) create_visibility_args=(--public); configure_visibility_args=(--public) ;;
              private) create_visibility_args=(); configure_visibility_args=(--private) ;;
              *)
                echo "attic-cache-bootstrap: unsupported visibility '$visibility' for cache '$cache_name'" >&2
                exit 1
                ;;
            esac

            if ! attic cache info "$cache_name" >/dev/null 2>&1; then
              attic cache create "''${create_visibility_args[@]}" --priority "$priority" "$cache_name"
              echo "attic-cache-bootstrap: created cache '$cache_name'."
            else
              echo "attic-cache-bootstrap: cache '$cache_name' already exists in atticd db; reusing."
            fi

            configure_args=("''${configure_visibility_args[@]}" --priority "$priority")
            case "$retention_mode" in
              attic-cache-retention-period)
                if [[ -z "$retention_period" ]]; then
                  echo "attic-cache-bootstrap: cache '$cache_name' has retention mode '$retention_mode' but no period" >&2
                  exit 1
                fi
                configure_args+=(--retention-period "$retention_period")
                ;;
              server-default) ;;
              attic-cache-reset-retention-period)
                configure_args+=(--reset-retention-period)
                ;;
              *)
                echo "attic-cache-bootstrap: unsupported retention mode '$retention_mode' for cache '$cache_name'" >&2
                exit 1
                ;;
            esac

            attic cache configure "''${configure_args[@]}" "$cache_name"
            echo "attic-cache-bootstrap: configured cache '$cache_name' (visibility=$visibility priority=$priority retention=$retention_mode''${retention_period:+:$retention_period})."

            cacheConfigJson=$(curl --silent --fail \
              --header "Authorization: Bearer $token" \
              "$localEndpoint""_api/v1/cache-config/$cache_name")

            publicKeyValue=$(printf '%s' "$cacheConfigJson" | jq -er '.public_key // empty')

            if [[ -z "$publicKeyValue" ]]; then
              echo "attic-cache-bootstrap: failed to extract public_key from cache-config response" >&2
              echo "  cache: $cache_name" >&2
              exit 1
            fi

            if [[ "$publicKeyValue" != "$cache_name:"* ]]; then
              echo "attic-cache-bootstrap: refusing to write a public key that does not name its cache." >&2
              exit 1
            fi

            tmpKey=$(mktemp "$publicKeyDir/.public-key.XXXXXX")
            printf '%s\n' "$publicKeyValue" > "$tmpKey"
            chmod 0644 "$tmpKey"
            mv -- "$tmpKey" "$public_key_file"

            if [[ "$cache_name" == ${lib.escapeShellArg primaryCacheName} ]]; then
              tmpLegacyKey=$(mktemp "$stateDir/.public-key.XXXXXX")
              printf '%s\n' "$publicKeyValue" > "$tmpLegacyKey"
              chmod 0644 "$tmpLegacyKey"
              mv -- "$tmpLegacyKey" "$publicKey"
            fi

            jq -cn \
              --arg name "$cache_name" \
              --arg publicKey "$publicKeyValue" \
              --arg publicKeyFile "$public_key_file" \
              --arg substituter "$substituter" \
              '{name: $name, publicKey: $publicKey, publicKeyFile: $publicKeyFile, substituter: $substituter}' \
              >> "$publicKeysJsonl"
          done

          jq -s \
            --arg endpoint "$publicEndpoint" \
            --slurpfile inventory "$stateInventory" \
            '{endpoint: $endpoint, primaryCache: $inventory[0].primaryCache, caches: $inventory[0].caches, publicKeys: .}' \
            "$publicKeysJsonl" \
            > "$publicKeysJson.tmp"
          chmod 0644 "$publicKeysJson.tmp"
          mv -- "$publicKeysJson.tmp" "$publicKeysJson"

          cp -- "$stateInventory" "$readableInventory.json.tmp" || true
          rm -f "$readableInventory.json.tmp"

          touch "$marker"
          echo "attic-cache-bootstrap: complete."
        '';
      };

      cacheType = lib.types.submodule (
        { ... }:
        {
          options = {
            name = lib.mkOption {
              type = lib.types.str;
              description = "Attic cache name (path segment under the endpoint).";
            };
            primary = lib.mkOption {
              type = lib.types.bool;
              default = false;
              description = "Marks the canonical cache (gets the legacy public-key.txt path).";
            };
            access = lib.mkOption {
              type = lib.types.enum [
                "netbird-token"
                "netbird-anon"
                "public-internet"
              ];
              description = ''
                Access policy. netbird-token = atticd --private (token-gated reads)
                behind the network ACL (two-credential). netbird-anon = atticd
                --public behind the network ACL (VPN membership authorizes reads).
                public-internet = atticd --public with unauthenticated internet GET
                (writes still restricted to the network ACL).
              '';
            };
            priority = lib.mkOption {
              type = lib.types.int;
              default = 41;
              description = "Substituter priority.";
            };
            retention = lib.mkOption {
              type = lib.types.enum [
                "server-default"
                "attic-cache-retention-period"
                "attic-cache-reset-retention-period"
              ];
              default = "server-default";
              description = "Retention policy mode.";
            };
            retentionPeriod = lib.mkOption {
              type = lib.types.nullOr lib.types.str;
              default = null;
              example = "6 months";
              description = "Required when retention = attic-cache-retention-period.";
            };
          };
        }
      );
    in
    {
      options.mcl.attic-cache-host = {
        enable = lib.mkEnableOption "the parametric Attic cache host (atticd + nginx + bootstrap)";
        domain = lib.mkOption {
          type = lib.types.str;
          example = "cache.metacraft-labs.com";
          description = "Public hostname for the cache vhost.";
        };
        port = lib.mkOption {
          type = lib.types.port;
          default = 8080;
          description = "Local atticd listen port (proxied by nginx).";
        };
        environmentFile = lib.mkOption {
          type = lib.types.path;
          description = "Path to the atticd HS256 environment file (e.g. an agenix-decrypted runtime path).";
        };
        networkAcl.allow = lib.mkOption {
          type = lib.types.listOf lib.types.str;
          example = [
            "100.64.0.0/10"
            "192.168.100.0/24"
          ];
          description = "Source CIDRs allowed by nginx for restricted paths (NetBird overlay + LAN). Empty keeps caches open per their access policy.";
        };
        caches = lib.mkOption {
          type = lib.types.listOf cacheType;
          description = "Caches to host. Exactly one must be marked primary.";
        };
      };

      config = lib.mkIf cfg.enable {
        assertions = [
          {
            assertion = lib.length (builtins.filter (c: c.primary) cfg.caches) == 1;
            message = "mcl.attic-cache-host: exactly one cache must be marked primary.";
          }
        ];

        environment.systemPackages = [ mcl-atticadm ];

        systemd.services.atticd.restartTriggers = [ cfg.environmentFile ];

        services.atticd = {
          enable = true;
          environmentFile = cfg.environmentFile;
          settings = {
            listen = "[::]:${toString port}";
            allowed-hosts = [
              domain
              "127.0.0.1:${toString port}"
              "[::1]:${toString port}"
            ];
            api-endpoint = "https://${domain}/";
          };
        };

        systemd.tmpfiles.rules = [
          "d ${bootstrapDir} 0755 root root -"
          "d ${bootstrapPublicKeyDir} 0755 root root -"
        ];

        systemd.services.attic-cache-bootstrap = {
          description = "Idempotent bootstrap of managed Attic caches";
          after = [
            "atticd.service"
            "network-online.target"
          ];
          wants = [ "network-online.target" ];
          wantedBy = [ "multi-user.target" ];
          serviceConfig = {
            Type = "oneshot";
            RemainAfterExit = true;
            ExecStart = "${cacheBootstrap}/bin/attic-cache-bootstrap";
            TimeoutStartSec = "120s";
          };
        };

        environment.etc."attic/metacraft-cache.env".text = ''
          ATTIC_ENDPOINT=https://${domain}/
          ATTIC_CACHE=${primaryCacheName}
          ATTIC_SUBSTITUTER=https://${domain}/${primaryCacheName}
          ATTIC_PUBLIC_KEY_FILE=${bootstrapPublicKey}
          ATTIC_MANAGED_CACHES_FILE=/etc/attic/managed-caches.json
        '';
        environment.etc."attic/managed-caches.json".text = managedCacheInventoryJson + "\n";
        environment.etc."attic/managed-caches.tsv".text = managedCacheInventoryTsv;

        services.nginx.commonHttpConfig = lib.mkAfter ''
          log_format mcl_attic_cache escape=json '{"time":"$time_iso8601","remote_addr":"$remote_addr","host":"$host","method":"$request_method","uri":"$request_uri","status":"$status","request_length":"$request_length","body_bytes_sent":"$body_bytes_sent","upstream_status":"$upstream_status","request_time":"$request_time","upstream_response_time":"$upstream_response_time"}';
        '';

        services.nginx.virtualHosts.${domain} = {
          forceSSL = true;
          enableACME = true;
          acmeRoot = null;
          locations =
            # Internet-readable caches: GET open, writes restricted to the ACL.
            (lib.optionalAttrs (internetReadCacheNames != [ ]) {
              "~ ^/(${lib.concatStringsSep "|" internetReadCacheNames})(/|$)" = {
                extraConfig = ''
                  access_log /var/log/nginx/attic-cache.access.jsonl mcl_attic_cache;
                  limit_except GET {
                    ${networkAcl}
                  }
                  client_max_body_size 10G;
                '';
                proxyPass = "http://127.0.0.1:${toString port}";
                proxyWebsockets = true;
              };
            })
            # Everything else (private + netbird-anon caches, the API, writes):
            # restricted to the network ACL on every method.
            // {
              "/" = {
                extraConfig = ''
                  access_log /var/log/nginx/attic-cache.access.jsonl mcl_attic_cache;
                  ${networkAcl}
                  client_max_body_size 10G;
                '';
                proxyPass = "http://127.0.0.1:${toString port}/";
                proxyWebsockets = true;
              };
            };
        };
        security.acme.certs.${domain} = { };
      };
    };
}
