# Alertmanager fleet routing — the GENERAL, parametric routing surface that
# makes the garm-fleet-alerts library actually PAGE.
#
# Runner-Fleet-Capability-Pools-And-Remote-Driving RE1 follow-up
# (`t_fleet_alert_routing`). RE1 shipped the Prometheus alert RULES with
# `severity` / `component` labels, but those labels were only a routing CONTRACT
# — there was no Alertmanager to honour them. This module is that missing piece,
# split per the campaign :repo_layering: — the company-agnostic routing helper
# lives here (nixos-modules); the concrete receivers / endpoints / secrets for a
# specific fleet live in that operator's `infra`.
#
# It wraps nixpkgs `services.prometheus.alertmanager` with an opinionated
# routing-by-(severity, component) tree rendered from the pure ./config.nix:
#
#   * `services.fleet-alert-routing` — renders ./config.nix with the operator's
#     receivers/thresholds into the Alertmanager `configuration`, and enables the
#     service. Receiver ENDPOINTS stay options (pager / webhook / Slack / email),
#     secrets are file-referenced (never inline).
#   * `packages.fleet-alertmanager-config` — the default-render, so the routing
#     is build-testable with `amtool` WITHOUT any infra (the gate
#     checks/alertmanager-routing.nix consumes it).
#
# The rendered config is generated by the pure ./config.nix so the file `amtool
# config routes test` replays is the exact file the host deploys — the same
# "render once, test the shipped artifact" discipline as garm-fleet-alerts.
{ ... }:
{
  perSystem =
    { pkgs, lib, ... }:
    {
      # Default-threshold render — convenience + the gate's input. YAML (which
      # amtool parses natively) built from the same pure config.nix the module
      # deploys.
      packages.fleet-alertmanager-config =
        (pkgs.formats.yaml { }).generate "alertmanager.yml"
          (import ./config.nix { inherit lib; });
    };

  flake.modules.nixos.alertmanager-fleet-routing =
    {
      config,
      lib,
      ...
    }:
    let
      cfg = config.services.fleet-alert-routing;
      inherit (lib)
        mkEnableOption
        mkOption
        mkIf
        types
        ;

      rendered = import ./config.nix {
        inherit lib;
        inherit (cfg)
          component
          criticalReceiver
          warningReceiver
          defaultReceiver
          receivers
          topGroupBy
          fleetGroupBy
          groupWait
          groupInterval
          repeatInterval
          global
          severityInhibit
          controllerDownInhibit
          controllerDownSourceMatchers
          extraInhibitRules
          extraRoutes
          ;
      };
    in
    {
      options.services.fleet-alert-routing = {
        enable = mkEnableOption "the fleet Alertmanager routing (severity -> pager/CI-ops, component grouping)";

        component = mkOption {
          type = types.str;
          default = "garm-fleet";
          description = "The `component` label value whose alerts are grouped together and eligible for the controller-down inhibition.";
        };

        criticalReceiver = mkOption {
          type = types.str;
          default = "pager";
          description = "Receiver name that `severity=critical` alerts route to (the on-call PAGER). Must be a key of `receivers`.";
        };
        warningReceiver = mkOption {
          type = types.str;
          default = "ci-ops";
          description = "Receiver name that `severity=warning` alerts route to (CI-ops). Must be a key of `receivers`.";
        };
        defaultReceiver = mkOption {
          type = types.str;
          default = "default";
          description = "Catch-all receiver for alerts matching neither severity bucket. Must be a key of `receivers`.";
        };

        receivers = mkOption {
          type = types.attrsOf (types.attrsOf types.anything);
          default = {
            "${cfg.defaultReceiver}" = { };
            "${cfg.criticalReceiver}".webhook_configs = [ { url = "http://127.0.0.1:9099/pager"; } ];
            "${cfg.warningReceiver}".webhook_configs = [ { url = "http://127.0.0.1:9099/ci-ops"; } ];
          };
          example = lib.literalExpression ''
            {
              default = { };
              pager.pagerduty_configs = [ { routing_key_file = config.age.secrets."alertmanager/pagerduty-key".path; } ];
              "ci-ops".slack_configs = [ {
                channel = "#ci-ops";
                api_url_file = config.age.secrets."alertmanager/slack-url".path;
              } ];
            }
          '';
          description = ''
            Pluggable receiver endpoints: name -> Alertmanager receiver config
            (the `name` field is derived from the key). Use the `*_file` secret
            variants (`routing_key_file`, `api_url_file`, …) — secrets are NEVER
            inlined here. The defaults are inert loopback webhooks so the module
            renders a valid, routable config without credentials; override for a
            real pager.
          '';
        };

        topGroupBy = mkOption {
          type = types.listOf types.str;
          default = [
            "alertname"
            "component"
          ];
          description = "`group_by` for the top-level route.";
        };
        fleetGroupBy = mkOption {
          type = types.listOf types.str;
          default = [
            "component"
            "severity"
          ];
          description = "`group_by` for the `component`-matched subtree — how the fleet's alerts are grouped together into pages.";
        };

        groupWait = mkOption {
          type = types.str;
          default = "30s";
          description = "Alertmanager `group_wait`.";
        };
        groupInterval = mkOption {
          type = types.str;
          default = "5m";
          description = "Alertmanager `group_interval`.";
        };
        repeatInterval = mkOption {
          type = types.str;
          default = "4h";
          description = "Alertmanager `repeat_interval`.";
        };

        global = mkOption {
          type = types.attrsOf types.anything;
          default = {
            resolve_timeout = "5m";
          };
          description = ''
            Alertmanager `global` block. Provider defaults live here (e.g.
            `smtp_smarthost`, `slack_api_url_file`, `pagerduty_url`). Secrets go
            through the `*_file` variants only.
          '';
        };

        severityInhibit = mkOption {
          type = types.bool;
          default = true;
          description = "Emit the classic squelch: a critical alert inhibits a warning alert with the same (component, instance).";
        };
        controllerDownInhibit = mkOption {
          type = types.bool;
          default = true;
          description = "Emit the controller-down inhibition: a controller-down alert inhibits its dependent `component` alerts on the same instance (page the cause, not the symptoms).";
        };
        controllerDownSourceMatchers = mkOption {
          type = types.listOf types.str;
          default = [ ''alertname="GarmControllerDown"'' ];
          description = "Source matchers identifying the controller-down alert for the controller-down inhibition (overridable / non-garm-specific).";
        };
        extraInhibitRules = mkOption {
          type = types.listOf (types.attrsOf types.anything);
          default = [ ];
          description = "Additional Alertmanager `inhibit_rules`.";
        };

        extraRoutes = mkOption {
          type = types.listOf (types.attrsOf types.anything);
          default = [ ];
          description = "Additional first-level routes, evaluated before the severity catch-alls (concrete per-team/per-org routing).";
        };

        listenAddress = mkOption {
          type = types.str;
          default = "127.0.0.1";
          description = "Address Alertmanager's web/API listens on. Keep it off the public internet (localhost, or a trusted overlay IP).";
        };
        port = mkOption {
          type = types.port;
          default = 9093;
          description = "Alertmanager web/API port.";
        };
      };

      config = mkIf cfg.enable {
        services.prometheus.alertmanager = {
          enable = true;
          inherit (cfg) listenAddress port;
          configuration = rendered;
        };
      };
    };
}
