{ ... }:
{
  imports = [
    ./ci-workflows.nix
    ./encrypted-s3-artifact.nix
    ./desktop-vms
    ./deployment-docs.nix
    ./deployment-cache.nix
    ./deployment-incus-rehearsal.nix
    ./deployment-monitoring.nix
    ./deployment-production-cutover.nix
    ./deployment-pull-agent.nix
    ./deployment-reconciler.nix
    ./garm-service-boot.nix
    ./garm-api-watchdog.nix
    ./garm-multi-provider.nix
    ./garm-reconcile.nix
    ./garm-incus-runner-host.nix
    ./garm-macos-runner-install-wrapper.nix
    ./garm-provider-vmharness-protocol.nix
    ./s3-artifact-store.nix
    ./repro-binary-cache-systemd.nix
    ./repro-binary-cache-cross-host.nix
    ./repro-cache-client-render.nix
    ./repro-lease-reaper-eval.nix
    ./repro-deploy-agent-https.nix
    ./consumer-flake-attic.nix
    ./linux-vm-cloud-init
    ./netbird-with-agenix.nix
    ./packages-ci-matrix.nix
    ./pre-commit.nix
    ./secret-integration
  ];
}
