name: Evaluate CI Matrix
description: Evaluate all packages, check cache status generate CI matrix and publish comment with the summary

inputs:
  is-initial:
    description: Is this the start of the CI workflow, or the end
    default: 'true'
    required: true
  cachix-cache:
    description: The name of the cachix cache to use
    required: true
  cachix-auth-token:
    description: Cachix auth token
    required: true
  trusted-public-keys:
    description: Trusted public keys
    required: true
  substituters:
    description: Substituters
    required: true
  comment_matrix:
    description: Whether to post a comment/upload the matrix
    required: false
    default: true
  precalc_matrix:
    description: Pre-calculated matrix
    required: true

outputs:
  matrix:
    description: 'Generated Matrix'
    value: ${{ steps.print-matrix.outputs.matrix }}
  comment:
    description: 'Comment'
    value: ${{ steps.print-matrix.outputs.comment }}

runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v9
      with:
        extra-conf: |
          accept-flake-config = true
          substituters = https://cache.nixos.org ${{inputs.substituters}}
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= ${{inputs.trusted-public-keys}}
          netrc-file = /home/runner/.config/nix/netrc
        nix-installer-tag: v0.15.1
    - name: Configure Nix
      shell: bash
      run: |
        mkdir -p /home/runner/.config/nix
        echo "machine ${{inputs.cachix-cache}}.cachix.org password ${{inputs.cachix-auth-token}}" >> /home/runner/.config/nix/netrc

    - name: Print CI Matrix
      id: print-matrix
      shell: bash
      env:
        IS_INITIAL: ${{ inputs.is-initial }}
        CACHIX_CACHE: ${{ inputs.cachix-cache }}
        CACHIX_AUTH_TOKEN: ${{ inputs.cachix-auth-token }}
        PRECALC_MATRIX: ${{ inputs.precalc_matrix }}
      run: nix run github:metacraft-labs/nixos-modules/feat/CD#print-table

    - name: Upload CI Matrix
      if: ${{ inputs.comment_matrix == true }}
      uses: actions/upload-artifact@v4
      with:
        name: matrix-${{ inputs.is-initial == 'true' && 'pre' || 'post' }}.json
        path: matrix-${{ inputs.is-initial == 'true' && 'pre' || 'post' }}.json

    - name: Update GitHub Comment
      if: ${{ inputs.comment_matrix == true }}
      uses: marocchino/sticky-pull-request-comment@v2.9.0
      with:
        path: comment.md
