name: Install Nix
description: Installs Nix and configures substituters and trusted public keys

inputs:
  cachix-cache:
    description: The name of the cachix cache to use
    required: true
  cachix-auth-token:
    description: Cachix auth token
    required: true
  trusted-public-keys:
    description: Trusted public keys
    required: false
    default: ''
  substituters:
    description: Substituters
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v27
      if: ${{ runner.environment == 'github-hosted' }}
      with:
        extra_nix_config: |
          accept-flake-config = true
          allow-import-from-derivation = true
          substituters = https://cache.nixos.org ${{inputs.substituters}}
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= ${{inputs.trusted-public-keys}}
          netrc-file = $HOME/.config/nix/netrc

    - name: Configure Nix
      if: ${{ runner.environment == 'github-hosted' }}
      shell: bash
      run: |
        mkdir -p $HOME/.config/nix
        {
          echo "machine ${{inputs.cachix-cache}}.cachix.org password ${{inputs.cachix-auth-token}}"
        } >> $HOME/.config/nix/netrc
