name: "MCL"

on:
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  mcl-test:
    runs-on: ubuntu-latest
    name: Build and test MCL
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
        with:
          extra-conf: accept-flake-config = true
          nix-installer-tag: v0.15.1

      - uses: cachix/cachix-action@v14
        with:
          name: ${{ vars.CACHIX_CACHE }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: ${{ vars.EXTRA_CACHIX_CACHES }}

      - name: Build and test MCL
        run: |
          set -euo pipefail
          nix build .#mcl
