name: 'Compare Disko NixOS configs'

on:
  # Allow this workflow to be reused by other workflows:
  workflow_call:
    inputs:
      runner:
        description: 'JSON-encoded list of runner labels'
        default: '["self-hosted"]'
        required: false
        type: string
    secrets:
      CACHIX_AUTH_TOKEN:
        description: 'Cachix auth token'
        required: true

jobs:
  post-initial-comment:
    runs-on: ${{ fromJSON(inputs.runner) }}
    steps:
      - name: 'Post initial disko status comment'
        uses: marocchino/sticky-pull-request-comment@v2.9.3
        with:
          recreate: true
          message: |
            Thanks for your Pull Request!

            This comment will be updated automatically with the status of disko on each machine.
  compare-disko-configs:
    runs-on: ${{ fromJSON(inputs.runner) }}
    name: 'Compare disko configs on machines'

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: metacraft-labs/nixos-modules/.github/install-nix@main
        with:
          cachix-cache: ${{ vars.CACHIX_CACHE }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Compare disko configurations
        env:
          CACHIX_CACHE: ${{ vars.CACHIX_CACHE }}
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
          # MCL_BRANCH: ${{ github.repository == 'metacraft-labs/nixos-modules' && github.sha || 'main' }}
          MCL_BRANCH: ${{ github.repository == 'metacraft-labs/nixos-modules' && github.sha || 'feat/compare-disko' }}
        run: nix run --accept-flake-config github:metacraft-labs/nixos-modules/${{ env.MCL_BRANCH }}#mcl compare_disko

  create-comment:
    runs-on: ${{ fromJSON(inputs.runner) }}
    name: 'Create comment'
    needs: [post-initial-comment, compare-disko-configs]

    steps:
      - name: Post Comment
        uses: marocchino/sticky-pull-request-comment@v2.9.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          recreate: true
          path: comment.md
