name: "Update Flake Packages ❄️"

on:
  # Allow this workflow to be reused by other workflows:
  workflow_call:

  # Allow this workflow to be triggered manually:
  workflow_dispatch:

  # Run everyday at 00:00:
  schedule:
    - cron: "0 0 * * *" # https://crontab.guru/#0_0_*_*_*

jobs:
  updateFlakePackages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        if: ${{ runner.environment == 'github-hosted' }}
        with:
          extra_nix_config: |
            accept-flake-config = true
            allow-import-from-derivation = true

      - uses: tibdex/github-app-token@v2.1.0
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Update flake packages
        uses: metacraft-labs/nix-update-action@main
        with:
          token: ${{ steps.generate-token.outputs.token }}
          blacklist: "ci-matrix,folder-size-metrics,mcl,grafana-agent,validator-ejector"
