name: "Update Flake Packages ❄️"

on:
  # Allow this workflow to be reused by other workflows:
  workflow_call:
    secrets:
      nix-github-token:
        description: GitHub token to add as access-token in nix.conf
        required: false
      APP_ID:
        description: ID of the GitHub App used for opening pull requests.
        required: true
      APP_PRIVATE_KEY:
        description: Private key of the GitHub App used for opening pull requests.
        required: true

  # Allow this workflow to be triggered manually:
  workflow_dispatch:

  # Run everyday at 00:00:
  schedule:
    - cron: "0 0 * * *" # https://crontab.guru/#0_0_*_*_*

jobs:
  updateFlakePackages:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        if: ${{ runner.environment == 'github-hosted' }}

      - name: Configure Nix
        shell: bash
        run: |
          mkdir -p $HOME/.config/nix
          {
            echo "${{ secrets.nix-github-token != '' && format('access-tokens = github.com={0}', secrets.nix-github-token) || '' }}
            accept-flake-config = true
            allow-import-from-derivation = true"
          } > $HOME/.config/nix/nix.conf

      - uses: tibdex/github-app-token@v2.1.0
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Update flake packages
        uses: metacraft-labs/nix-update-action@main
        with:
          token: ${{ steps.generate-token.outputs.token }}
          blacklist: "ci-matrix,folder-size-metrics,mcl,grafana-agent,validator-ejector"
