name: "Update Flake Packages ❄️"
on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "0 0 * * *" # https://crontab.guru/#0_0_*_*_*
jobs:
  updateFlakePackages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
        with:
          extra-conf: |
            accept-flake-config = true
            allow-import-from-derivation = true

      - uses: tibdex/github-app-token@v2.1.0
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Update flake packages
        uses: metacraft-labs/nix-update-action@main
        with:
          token: ${{ steps.generate-token.outputs.token }}
          unstable: ""
          from_branch: "cardano, graphql, eos-vm"
          blacklist: "circ,circom,corepack-shims,cosmos-theta-testnet,emscripten,eos-vm,ffiasm,go-opera,polkadot,polkadot-fast,solana,solana-rust-artifacts,zqfield-bn254,wasmd,rapidsnark,rapidsnark-server,pistache,cryptography36"
